name: openapi_spec
description: OpenAPI specification parser for APIdash
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  yaml: ^3.1.2
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  seed: ^0.0.3 
  apidash_core:
    path: ../apidash_core

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0